[workspace]
members = [
    "1-0-hello-world",
    "1-1-0-comments",
    "1-2-0-formatted-print",
    "1-2-1-debug",
    "1-2-2-display",
    "1-2-3-formatting",

    "2-2-tuples",
    "2-3-arrays_and_slices",

    "3-2-0-enums",
    "3-2-3-linked_list",
]
